apiVersion: spec.keptn.sh/0.1.4
kind: Remediation
metadata:
  name: helloservice-remediation

spec:
  remediations:
    - problemType: number_of_errors

      actionsOnOpen:
        - name: Fallback to previous version using helm
          action: fallback
          description: Scale up
          value: 
            defaultApp: "kuro08/zero:0.2.0"