apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeroservice.fullname" . }}
  labels:
    {{- include "zeroservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "zeroservice.selectorLabels" . | nindent 4 }}
